### ISSUE TITLE
Error: text format parsing error in line 1: invalid metric name

### ISSUE THREAD

**Issue by bsushant-athena** [ahus1/prometheus-hystrix#15]
My configuration: 
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: "gatewaymonitor"

scrape_configs:
  - job_name: "gateway"
    metrics_path: "/public/metrics"

    static_configs:
      - targets: ["10.8.110.83:18888"]
```

I'm using spring cloud zuul/hystrix/ribbon all the netflix oss.
I'm able to see the hystrix metrics at http://localhost:18888/public/metrics
I'm not able to see issue with my prometheus.yml. 
The error I'm getting: https://ibb.co/hDXR5w
Please help.
